//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string motivo { get; set; }
        public Nullable<int> mascota_id { get; set; }
        public Nullable<int> empleado_id { get; set; }
        public Nullable<int> sede_id { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Mascota Mascota { get; set; }
        public virtual Sede Sede { get; set; }
    }
}
