//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int id { get; set; }
        public Nullable<int> costo_total { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> servicio_id { get; set; }
        public Nullable<int> medicamento_id { get; set; }
    
        public virtual Medicamento Medicamento { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
