//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicio()
        {
            this.Pagoes = new HashSet<Pago>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public Nullable<int> mascota_id { get; set; }
        public Nullable<int> empleado_id { get; set; }
        public Nullable<int> consultorio_id { get; set; }
        public Nullable<int> tipoServicio_id { get; set; }
    
        public virtual Consultorio Consultorio { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Mascota Mascota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pagoes { get; set; }
        public virtual TipoServicio TipoServicio { get; set; }
    }
}
