//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinariaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id { get; set; }
        public string userName { get; set; }
        public string contraseña { get; set; }
        public string salt { get; set; }
        public Nullable<int> empleado_id { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
